/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qrgzy9hj6GGeC381EGfELp
// Component: kkxlbgxqmBw1

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button2 from "../../Button2"; // plasmic-import: 08WU9IokPT6n/component
import Button from "../../Button"; // plasmic-import: jt2j7CHc7KBU/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: qrgzy9hj6GGeC381EGfELp/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: qrgzy9hj6GGeC381EGfELp/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: qrgzy9hj6GGeC381EGfELp/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: kkxlbgxqmBw1/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: HL2cx3XqKX6Z/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: XRWVBDzNjWYR/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: IdyPZ2PRL2vb/icon
import ArrowDownSvgIcon from "./icons/PlasmicIcon__ArrowDownSvg"; // plasmic-import: 2QZVkZITGcT-/icon
import Icon11Icon from "./icons/PlasmicIcon__Icon11"; // plasmic-import: sepMKIxIwKMh/icon
import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: tq99IOsRzckU/icon
import Icon12Icon from "./icons/PlasmicIcon__Icon12"; // plasmic-import: s914vYWcBu51/icon
import Icon13Icon from "./icons/PlasmicIcon__Icon13"; // plasmic-import: 0o9AoJxfY-ed/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: ohR3gSoG6pR2/icon
import Icon19Icon from "./icons/PlasmicIcon__Icon19"; // plasmic-import: GloFZO7DAKCR/icon
import Icon17Icon from "./icons/PlasmicIcon__Icon17"; // plasmic-import: 7W9T4txEOvuQ/icon
import Icon20Icon from "./icons/PlasmicIcon__Icon20"; // plasmic-import: UKWF1bySvIgm/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  foreground2?: Flex__<"div">;
  h1?: Flex__<"h1">;
  registerLink?: Flex__<typeof Button2>;
  foreground?: Flex__<"div">;
  foreground3?: Flex__<"div">;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicHomepage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={PlasmicHomepage.pageMetadata.title}
        />

        <meta
          key="og:image"
          property="og:image"
          content={PlasmicHomepage.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={PlasmicHomepage.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox___82Orh)}>
            <div className={classNames(projectcss.all, sty.freeBox__q4Oin)}>
              <div className={classNames(projectcss.all, sty.freeBox__zot9V)}>
                <div className={classNames(projectcss.all, sty.freeBox__aytnG)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__q0Xwn)}
                    displayHeight={"default"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"96px"}
                    src={{
                      src: "/plasmic/kinect_academy_inc/images/kinectIconLightPng.png",
                      fullWidth: 1000,
                      fullHeight: 1000,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__uhYpx)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__boAwQ
                      )}
                      component={Link}
                      href={`/`}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__mxhDd)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___1Erk
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Services"
                          : "HOME"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__d8Vuy)}
                          role={"img"}
                        />
                      ) : null}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__pbOwj
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__xr1X)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__a6KnN
                        )}
                      >
                        {"Features"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__n51Y0)}
                          role={"img"}
                        />
                      ) : null}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___970O
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___1PsEq
                          )}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pkd4X
                        )}
                      >
                        {"work"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__fA331)}
                          role={"img"}
                        />
                      ) : null}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link___3MgSo
                      )}
                      component={Link}
                      href={`/contact`}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__pLjgD)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__q1AId
                        )}
                      >
                        {"Contact"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___7VmG5
                          )}
                          role={"img"}
                        />
                      ) : null}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__fQsii
                      )}
                      component={Link}
                      href={`/about-us`}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__yMJs1)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__r66N1
                        )}
                      >
                        {"About"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__ePqzD)}
                          role={"img"}
                        />
                      ) : null}
                    </PlasmicLink__>
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___0I6BE)}
                >
                  <button
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      projectcss.__wab_text,
                      sty.button__svrIc
                    )}
                  >
                    {"Sign up"}
                  </button>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__wWs4V
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg___3Rx3J)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eKjWb
                      )}
                    >
                      {"Log in"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__wy4Kg)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              className={classNames(projectcss.all, sty.foreground2)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__yRIu)}>
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{"Join the "}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "var(--token-Dd6gyjIVe7XT)" }}
                    >
                      {"Kinect"}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#51D1FF" }}
                    >
                      {" Academy"}
                    </span>
                    <React.Fragment>{" Family!"}</React.Fragment>
                  </React.Fragment>
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4ItLm
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "var(--token-Dd6gyjIVe7XT)" }}
                    >
                      {"SENIOR HIGH SCHOOL | GAPAN CITY"}
                    </span>
                  </React.Fragment>
                </div>
                <Button2
                  data-plasmic-name={"registerLink"}
                  data-plasmic-override={overrides.registerLink}
                  className={classNames("__wab_instance", sty.registerLink)}
                  disabled={false}
                  end={
                    <Icon6Icon
                      className={classNames(projectcss.all, sty.svg__mztV2)}
                      role={"img"}
                    />
                  }
                  iconEnd={true}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ccrkL
                      )}
                    >
                      {"REGISTER NOW"}
                    </div>
                  }
                  linkTo={"https://forms.gle/rse2ggxXWFjCuugY9"}
                  onClick={async event => {
                    const $steps = {};

                    $steps["runElementAction"] = true
                      ? (() => {
                          const actionArgs = {};
                          return (({ tplRef, action, args }) => {
                            return $refs?.[tplRef]?.[action]?.(...(args ?? []));
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["runElementAction"] != null &&
                      typeof $steps["runElementAction"] === "object" &&
                      typeof $steps["runElementAction"].then === "function"
                    ) {
                      $steps["runElementAction"] =
                        await $steps["runElementAction"];
                    }
                  }}
                  openLinkInNewTab={true}
                  roundedFull={true}
                  size={"large"}
                  start={
                    <Icon4Icon
                      className={classNames(projectcss.all, sty.svg__bspZp)}
                      role={"img"}
                    />
                  }
                  type={"soft"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__tHIju)}>
                <ArrowDownSvgIcon
                  className={classNames(projectcss.all, sty.svg__qt37N)}
                  role={"img"}
                />
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___72Tsq)}>
            <div className={classNames(projectcss.all, sty.freeBox___67NlN)}>
              <div className={classNames(projectcss.all, sty.freeBox__udQvv)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__vcPwu)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/kinect_academy_inc/images/groupPhoto2023Png.png",
                    fullWidth: 3799,
                    fullHeight: 1995,
                    aspectRatio: undefined
                  }}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0IovM
                  )}
                >
                  {"SERVICES"}
                </div>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__tmW09
                  )}
                >
                  {"What do we offer?"}
                </h2>
                <section
                  className={classNames(projectcss.all, sty.section__hraNe)}
                >
                  <div
                    data-plasmic-name={"foreground"}
                    data-plasmic-override={overrides.foreground}
                    className={classNames(projectcss.all, sty.foreground)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__uh24X)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__xGzHq
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__k6Tu
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__puolL
                            )}
                          >
                            <Icon11Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__lKVy1
                              )}
                              role={"img"}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___9PRpS
                              )}
                            >
                              <Icon8Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__awunN
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__zyBk5
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3___4CxSf
                              )}
                            >
                              {"FACILITIES"}
                            </h3>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ljn4I
                              )}
                            >
                              {"Fully air-conditioned clean classrooms."}
                            </div>
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__y53Xj
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__xXa4Q
                            )}
                          >
                            <Icon12Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__s9L39
                              )}
                              role={"img"}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__lhTdw
                              )}
                            >
                              <Icon8Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__mtXue
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__lYceE
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__sebwr
                              )}
                            >
                              {"CHARACTER"}
                            </h3>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__phahD
                              )}
                            >
                              {
                                "We teach not just intelligence, but Godly character and ethics."
                              }
                            </div>
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__liMxO
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__s572P
                            )}
                          >
                            <Icon13Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__hJ8Tv
                              )}
                              role={"img"}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__aQlvc
                              )}
                            >
                              <Icon8Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__wDnM8
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__zTg0I
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__etxDk
                              )}
                            >
                              {"EDUCATION"}
                            </h3>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___8Dz3I
                              )}
                            >
                              {
                                "Our teachers adapt to every student to reach their full potential."
                              }
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__ykA7Y)}>
            <div className={classNames(projectcss.all, sty.freeBox__aYemm)}>
              <div className={classNames(projectcss.all, sty.freeBox___7Klzb)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lS1Q
                  )}
                >
                  {"WORK"}
                </div>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__jwgYj
                  )}
                >
                  {"Let our work speak for itself."}
                </h2>
                <section
                  className={classNames(projectcss.all, sty.section__xAGzp)}
                >
                  <div
                    data-plasmic-name={"foreground3"}
                    data-plasmic-override={overrides.foreground3}
                    className={classNames(projectcss.all, sty.foreground3)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__yqT7U)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__bdVUk
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__fHtkv
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__vdKsA
                            )}
                          >
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__byUPn)}
                              displayHeight={"auto"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/kinect_academy_inc/images/pexelsTimMossholder1154739Jpg.jpg",
                                fullWidth: 1920,
                                fullHeight: 1280,
                                aspectRatio: undefined
                              }}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___3DB0
                              )}
                            >
                              <Icon8Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__g4CrD
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__xPe2R
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__dNeGe
                              )}
                            >
                              {"Heading main Lorem"}
                            </h3>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__qmTu9
                              )}
                            >
                              {
                                "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the "
                              }
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__aP4K3
                              )}
                            >
                              <Button color={"softYellow"} submitsForm={true}>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__oIr3M
                                  )}
                                >
                                  {"Read More"}
                                </div>
                              </Button>
                            </div>
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ykFzW
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__q9Yo
                            )}
                          >
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__vwnNh)}
                              displayHeight={"auto"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/kinect_academy_inc/images/pexelsSolomanSoh1492232Jpg.jpg",
                                fullWidth: 4000,
                                fullHeight: 2667,
                                aspectRatio: undefined
                              }}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___0W9Dk
                              )}
                            >
                              <Icon8Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__iFoNf
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___5XxRh
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__bpdoz
                              )}
                            >
                              {"Heading main Lorem"}
                            </h3>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__vpg1S
                              )}
                            >
                              {
                                "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the "
                              }
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__j8Pey
                              )}
                            >
                              <Button color={"softYellow"} submitsForm={true}>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__qcIll
                                  )}
                                >
                                  {"Read More"}
                                </div>
                              </Button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__c0Xy4)}>
            <div className={classNames(projectcss.all, sty.freeBox__ebcT)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gFzmT
                )}
              >
                {"CLIENTS"}
              </div>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__ypCO
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Our Client brands"
                  : "We've been lucky to work with some great companies."}
              </h2>
              <div className={classNames(projectcss.all, sty.freeBox__ulYwH)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__lQe3B)}
                  displayHeight={"48px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={
                    "https://plasmic-ray.s3.us-west-2.amazonaws.com/logo-loom.svg"
                  }
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__bbRbh)}
                  displayHeight={"48px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={
                    "https://plasmic-ray.s3.us-west-2.amazonaws.com/logo-strapi.svg"
                  }
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__q0Y6T)}
                  displayHeight={"48px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={
                    "https://plasmic-ray.s3.us-west-2.amazonaws.com/logo-segment.svg"
                  }
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___91XYd)}
                  displayHeight={"48px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={
                    "https://plasmic-ray.s3.us-west-2.amazonaws.com/logo-xstate.svg"
                  }
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__kVtpp)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__g7Is9)}
                  displayHeight={"96px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"96px"}
                  src={
                    "https://www.caa.com/sites/default/files/styles/headshot_500x500/public/speaker-headshots/Morgan_CAAspeakers_Heashot_Web.jpg?itok=WCOhQ1Hj"
                  }
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kYxaa
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. "
                  }
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sQf9S
                  )}
                >
                  {"Lorem, TGS"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uUdD1
                  )}
                >
                  {"Company name lorem"}
                </div>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__baVbu)}>
            <div className={classNames(projectcss.all, sty.freeBox__iik3U)}>
              <div className={classNames(projectcss.all, sty.freeBox___5Ho9D)}>
                <div className={classNames(projectcss.all, sty.freeBox__z4Ubu)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__do5Cy)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"200px"}
                    src={{
                      src: "/plasmic/kinect_academy_inc/images/kinectLogoLightPng.png",
                      fullWidth: 1800,
                      fullHeight: 636,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__fbxw9)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cmeTk
                      )}
                    >
                      {"Connect with us"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__hnEY)}
                    >
                      <Icon19Icon
                        className={classNames(projectcss.all, sty.svg__rHbfH)}
                        onClick={async event => {
                          const $steps = {};

                          $steps["goToHttpsWwwFacebookComKinectacademyph"] =
                            true
                              ? (() => {
                                  const actionArgs = {
                                    destination:
                                      "https://www.facebook.com/kinectacademyph"
                                  };
                                  return (({ destination }) => {
                                    if (
                                      typeof destination === "string" &&
                                      destination.startsWith("#")
                                    ) {
                                      document
                                        .getElementById(destination.substr(1))
                                        .scrollIntoView({ behavior: "smooth" });
                                    } else {
                                      __nextRouter?.push(destination);
                                    }
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                          if (
                            $steps["goToHttpsWwwFacebookComKinectacademyph"] !=
                              null &&
                            typeof $steps[
                              "goToHttpsWwwFacebookComKinectacademyph"
                            ] === "object" &&
                            typeof $steps[
                              "goToHttpsWwwFacebookComKinectacademyph"
                            ].then === "function"
                          ) {
                            $steps["goToHttpsWwwFacebookComKinectacademyph"] =
                              await $steps[
                                "goToHttpsWwwFacebookComKinectacademyph"
                              ];
                          }
                        }}
                        role={"img"}
                      />

                      <Icon17Icon
                        className={classNames(projectcss.all, sty.svg__faA6)}
                        onClick={async event => {
                          const $steps = {};

                          $steps["goToHttpsMMeKinectacademyph"] = true
                            ? (() => {
                                const actionArgs = {
                                  destination: "https://m.me/kinectacademyph"
                                };
                                return (({ destination }) => {
                                  if (
                                    typeof destination === "string" &&
                                    destination.startsWith("#")
                                  ) {
                                    document
                                      .getElementById(destination.substr(1))
                                      .scrollIntoView({ behavior: "smooth" });
                                  } else {
                                    __nextRouter?.push(destination);
                                  }
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["goToHttpsMMeKinectacademyph"] != null &&
                            typeof $steps["goToHttpsMMeKinectacademyph"] ===
                              "object" &&
                            typeof $steps["goToHttpsMMeKinectacademyph"]
                              .then === "function"
                          ) {
                            $steps["goToHttpsMMeKinectacademyph"] =
                              await $steps["goToHttpsMMeKinectacademyph"];
                          }
                        }}
                        role={"img"}
                      />

                      <Icon20Icon
                        className={classNames(projectcss.all, sty.svg__ty1Zz)}
                        onClick={async event => {
                          const $steps = {};

                          $steps["goToHttpsWwwYoutubeComKinectacademyVideos"] =
                            true
                              ? (() => {
                                  const actionArgs = {
                                    destination:
                                      "https://www.youtube.com/@kinectacademy/videos"
                                  };
                                  return (({ destination }) => {
                                    if (
                                      typeof destination === "string" &&
                                      destination.startsWith("#")
                                    ) {
                                      document
                                        .getElementById(destination.substr(1))
                                        .scrollIntoView({ behavior: "smooth" });
                                    } else {
                                      __nextRouter?.push(destination);
                                    }
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                          if (
                            $steps[
                              "goToHttpsWwwYoutubeComKinectacademyVideos"
                            ] != null &&
                            typeof $steps[
                              "goToHttpsWwwYoutubeComKinectacademyVideos"
                            ] === "object" &&
                            typeof $steps[
                              "goToHttpsWwwYoutubeComKinectacademyVideos"
                            ].then === "function"
                          ) {
                            $steps[
                              "goToHttpsWwwYoutubeComKinectacademyVideos"
                            ] =
                              await $steps[
                                "goToHttpsWwwYoutubeComKinectacademyVideos"
                              ];
                          }
                        }}
                        role={"img"}
                      />
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__gdJz)}>
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__aVhw1
                    )}
                  >
                    {"Navigation"}
                  </h3>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__wxIi
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__szPgk)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___8Ajky
                      )}
                    >
                      {"Nav link"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__rFqkt)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link___65YZr
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__gQy5P)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vb62P
                      )}
                    >
                      {"Nav link"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg___9XWwC)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__resN2
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg___99Ey0)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bnqbM
                      )}
                    >
                      {"Nav link"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__qDSa9)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__zvaLy)}>
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__kw8Fk
                    )}
                  >
                    {"Support"}
                  </h3>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__mzkXd
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__oGoPe)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tAjl
                      )}
                    >
                      {"Link"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__haqib)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link___3OdBi
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__z9DcL)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ioHvR
                      )}
                    >
                      {"FAQs"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__v2QNs)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__pMb82
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg___7FBe)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nYtq3
                      )}
                    >
                      {"Status"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__furOc)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__f3W9
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__knLSx)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6U5Sy
                      )}
                    >
                      {"Link"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg___63MeM)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__zAAgY)}>
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__oe8Rh
                    )}
                  >
                    {"Address"}
                  </h3>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bEneW
                    )}
                  >
                    {"574 Delos Reyes St.\nSan Vicente, Gapan City"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8KwBx
                    )}
                  >
                    {"Phone:  0926.245.6828"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__p23Yv
                    )}
                  >
                    {"Email:  kinectacademy@gmail.com"}
                  </div>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__tlLo
                )}
              >
                <React.Fragment>
                  <React.Fragment>
                    {
                      "\u00a9 Kinect Academy Inc. All rights reserved. Site proudly built with "
                    }
                  </React.Fragment>
                  {
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        projectcss.plasmic_default__inline,
                        sty.link___9PwRj
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Plasmic"}
                    </PlasmicLink__>
                  }
                  <React.Fragment>{"."}</React.Fragment>
                </React.Fragment>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "foreground2",
    "h1",
    "registerLink",
    "foreground",
    "foreground3"
  ],
  foreground2: ["foreground2", "h1", "registerLink"],
  h1: ["h1"],
  registerLink: ["registerLink"],
  foreground: ["foreground"],
  foreground3: ["foreground3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  foreground2: "div";
  h1: "h1";
  registerLink: typeof Button2;
  foreground: "div";
  foreground3: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    foreground2: makeNodeComponent("foreground2"),
    h1: makeNodeComponent("h1"),
    registerLink: makeNodeComponent("registerLink"),
    foreground: makeNodeComponent("foreground"),
    foreground3: makeNodeComponent("foreground3"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Home | Kinect Academy Inc.",
      description: "",
      ogImageSrc:
        "https://site-assets.plasmic.app/4c83f9f70da81d0a474d8d59d6e1dc3e.png",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
