/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qrgzy9hj6GGeC381EGfELp
// Component: JX1k51GgglQQ

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button2 from "../../Button2"; // plasmic-import: 08WU9IokPT6n/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import Button from "../../Button"; // plasmic-import: jt2j7CHc7KBU/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: qrgzy9hj6GGeC381EGfELp/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: qrgzy9hj6GGeC381EGfELp/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: qrgzy9hj6GGeC381EGfELp/projectcss
import sty from "./PlasmicAboutUs.module.css"; // plasmic-import: JX1k51GgglQQ/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: HL2cx3XqKX6Z/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: XRWVBDzNjWYR/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: IdyPZ2PRL2vb/icon
import ArrowDownSvgIcon from "./icons/PlasmicIcon__ArrowDownSvg"; // plasmic-import: 2QZVkZITGcT-/icon
import Icon15Icon from "./icons/PlasmicIcon__Icon15"; // plasmic-import: ptEeGwwDFAnw/icon
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: 5VS5c4WaG97g/icon
import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: tq99IOsRzckU/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: ohR3gSoG6pR2/icon
import Icon19Icon from "./icons/PlasmicIcon__Icon19"; // plasmic-import: GloFZO7DAKCR/icon
import Icon17Icon from "./icons/PlasmicIcon__Icon17"; // plasmic-import: 7W9T4txEOvuQ/icon
import Icon20Icon from "./icons/PlasmicIcon__Icon20"; // plasmic-import: UKWF1bySvIgm/icon

createPlasmicElementProxy;

export type PlasmicAboutUs__VariantMembers = {};
export type PlasmicAboutUs__VariantsArgs = {};
type VariantPropType = keyof PlasmicAboutUs__VariantsArgs;
export const PlasmicAboutUs__VariantProps = new Array<VariantPropType>();

export type PlasmicAboutUs__ArgsType = {};
type ArgPropType = keyof PlasmicAboutUs__ArgsType;
export const PlasmicAboutUs__ArgProps = new Array<ArgPropType>();

export type PlasmicAboutUs__OverridesType = {
  root?: Flex__<"div">;
  foreground2?: Flex__<"div">;
  registerLink?: Flex__<typeof Button2>;
  reveal?: Flex__<typeof Reveal>;
  foreground?: Flex__<"div">;
  foreground3?: Flex__<"div">;
};

export interface DefaultAboutUsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicAboutUs__RenderFunc(props: {
  variants: PlasmicAboutUs__VariantsArgs;
  args: PlasmicAboutUs__ArgsType;
  overrides: PlasmicAboutUs__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicAboutUs.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicAboutUs.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={PlasmicAboutUs.pageMetadata.title}
        />

        <meta
          key="og:image"
          property="og:image"
          content={PlasmicAboutUs.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={PlasmicAboutUs.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__mqSfL)}>
            <div className={classNames(projectcss.all, sty.freeBox___0MMxs)}>
              <div className={classNames(projectcss.all, sty.freeBox__haVy9)}>
                <div className={classNames(projectcss.all, sty.freeBox__haUl7)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__b3Dlz)}
                    displayHeight={"default"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"96px"}
                    src={{
                      src: "/plasmic/kinect_academy_inc/images/kinectIconLightPng.png",
                      fullWidth: 1000,
                      fullHeight: 1000,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__xywXt)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__uUfyF
                      )}
                      component={Link}
                      href={`/`}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__h2Ig3)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qo7UX
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Services"
                          : "HOME"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__lpztE)}
                          role={"img"}
                        />
                      ) : null}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__frgj
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__vImFe)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__q64I
                        )}
                      >
                        {"Features"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__h86C)}
                          role={"img"}
                        />
                      ) : null}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__xy4Wd
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___5CdQ9
                          )}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uiSig
                        )}
                      >
                        {"work"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__cgdxx)}
                          role={"img"}
                        />
                      ) : null}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__uqhR3
                      )}
                      component={Link}
                      href={`/contact`}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__zUFff)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jRiUz
                        )}
                      >
                        {"Contact"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__rx4Ek)}
                          role={"img"}
                        />
                      ) : null}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__q27K
                      )}
                      component={Link}
                      href={`/about-us`}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__rEoN)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zeXvY
                        )}
                      >
                        {"About"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__yVpCu)}
                          role={"img"}
                        />
                      ) : null}
                    </PlasmicLink__>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__seGo)}>
                  <button
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      projectcss.__wab_text,
                      sty.button__kgaRc
                    )}
                  >
                    {"Sign up"}
                  </button>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__cp1Xo
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__cbWqc)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hszMw
                      )}
                    >
                      {"Log in"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__vziVt)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              className={classNames(projectcss.all, sty.foreground2)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__yS8Fr)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__vwtb4
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{"Join the "}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "var(--token-Dd6gyjIVe7XT)" }}
                    >
                      {"Kinect"}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#51D1FF" }}
                    >
                      {" Academy"}
                    </span>
                    <React.Fragment>{" Family!"}</React.Fragment>
                  </React.Fragment>
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mWfQp
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "var(--token-Dd6gyjIVe7XT)" }}
                    >
                      {"SENIOR HIGH SCHOOL | GAPAN CITY"}
                    </span>
                  </React.Fragment>
                </div>
                <Button2
                  data-plasmic-name={"registerLink"}
                  data-plasmic-override={overrides.registerLink}
                  className={classNames("__wab_instance", sty.registerLink)}
                  disabled={false}
                  end={
                    <Icon6Icon
                      className={classNames(projectcss.all, sty.svg__e5ZsA)}
                      role={"img"}
                    />
                  }
                  iconEnd={true}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__m6Hpx
                      )}
                    >
                      {"REGISTER NOW"}
                    </div>
                  }
                  linkTo={"https://forms.gle/rse2ggxXWFjCuugY9"}
                  onClick={async event => {
                    const $steps = {};

                    $steps["runElementAction"] = true
                      ? (() => {
                          const actionArgs = {};
                          return (({ tplRef, action, args }) => {
                            return $refs?.[tplRef]?.[action]?.(...(args ?? []));
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["runElementAction"] != null &&
                      typeof $steps["runElementAction"] === "object" &&
                      typeof $steps["runElementAction"].then === "function"
                    ) {
                      $steps["runElementAction"] =
                        await $steps["runElementAction"];
                    }
                  }}
                  openLinkInNewTab={true}
                  roundedFull={true}
                  size={"small"}
                  start={
                    <Icon4Icon
                      className={classNames(projectcss.all, sty.svg___5D2S6)}
                      role={"img"}
                    />
                  }
                  type={"soft"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__xcgIg)}>
                <ArrowDownSvgIcon
                  className={classNames(projectcss.all, sty.svg__zhq95)}
                  role={"img"}
                />
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__twUc)}>
            <Reveal
              data-plasmic-name={"reveal"}
              data-plasmic-override={overrides.reveal}
              cascade={true}
              className={classNames("__wab_instance", sty.reveal)}
              triggerOnce={true}
            >
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__ckSaZ)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={"https://placekitten.com/300/200"}
              />

              <div className={classNames(projectcss.all, sty.freeBox__bfmLl)}>
                <div className={classNames(projectcss.all, sty.freeBox__l2OX)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rZgxV
                    )}
                  >
                    {"About Us"}
                  </div>
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__f94
                    )}
                  >
                    {"Who is Kinect Academy ?"}
                  </h2>
                  <section
                    className={classNames(projectcss.all, sty.section__phMtY)}
                  >
                    <div
                      data-plasmic-name={"foreground"}
                      data-plasmic-override={overrides.foreground}
                      className={classNames(projectcss.all, sty.foreground)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__y6S8
                        )}
                      >
                        <h1
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1__sgxzz
                          )}
                        >
                          {"Our Journey & Purpose"}
                        </h1>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zFd
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"The Heart of Our Institution\r"}
                            </span>
                            <React.Fragment>
                              {
                                "\n\r\nKinect Academy Inc. is a non-stock, non-profit private educational institution rooted in Gapan City, Nueva Ecija. We believe that education is more than just a profit-driven endeavor; it is a mission to touch lives and prepare the youth for a purposeful future.\n\n\r\n"
                              }
                            </React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"Born from a National Vision\r"}
                            </span>
                            <React.Fragment>
                              {
                                "\n\r\nIn 2014, as the Philippines embarked on the historic K-to-12 transition, Kinect Academy was founded with a clear intent: to support the nation\u2019s youth through this major educational shift.\r\n\r\nWhat started in 2016 as a specialized Senior High School has since evolved into a center for higher learning. In 2020, we officially partnered with the Commission on Higher Education (CHED) to offer college degrees that bridge the gap between classroom learning and professional careers.\n\n\r\n"
                              }
                            </React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 700 }}
                            >
                              {"Excellence, Innovation, and Character\r"}
                            </span>
                            <React.Fragment>
                              {
                                "\n\r\nAt Kinect, we provide more than just diplomas. We equip our students with a dual-edged advantage:\r\n\r\n    Practical Expertise: Our curriculum is designed to provide real-world skills through updated courses like BS in Office Administration (BSOA) and Bachelor of Technical Vocational Teacher Education (BTVTEd).\r\n\r\n    Godly Character: Beyond academic intelligence, we instill the morals and standards vital for a successful life. We strive to nurture responsible, God-fearing individuals who lead with integrity."
                              }
                            </React.Fragment>
                          </React.Fragment>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__b0UiW
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__ye56M
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__qx0M
                              )}
                            >
                              <Icon15Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__jfOW
                                )}
                                role={"img"}
                              />
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__xGshd
                              )}
                            >
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__mZnE
                                )}
                              >
                                {"Our Mission"}
                              </h3>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___2AhGo
                                )}
                              >
                                {
                                  "Our Mission is to educate and enrich the knowledge of every individual through the discovering and enhancing of their skills, while building Godly character as their core foundation."
                                }
                              </div>
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__tkLh
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__iiiRq
                              )}
                            >
                              <Icon14Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___7Ccl9
                                )}
                                role={"img"}
                              />
                            </div>
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__ybw1E
                                )}
                              >
                                <Icon8Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__ppSr
                                  )}
                                  role={"img"}
                                />
                              </div>
                            ) : null}
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___6Lr9T
                              )}
                            >
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__ykATk
                                )}
                              >
                                {"Our Vision"}
                              </h3>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__go70Z
                                )}
                              >
                                {
                                  "Our Vision is to become an influential educational institution, known for actively providing high academic standards while instilling Godly Character and Values that will make a difference in our society."
                                }
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </section>
                </div>
              </div>
            </Reveal>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___9WJrz)}>
            <div className={classNames(projectcss.all, sty.freeBox__uZUzq)}>
              <div className={classNames(projectcss.all, sty.freeBox__uxsMw)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__o5Esk
                  )}
                >
                  {"WORK"}
                </div>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__eThI5
                  )}
                >
                  {"Let our work speak for itself."}
                </h2>
                <section
                  className={classNames(projectcss.all, sty.section___7GtU)}
                >
                  <div
                    data-plasmic-name={"foreground3"}
                    data-plasmic-override={overrides.foreground3}
                    className={classNames(projectcss.all, sty.foreground3)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__wmbIf)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__hvVpJ
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__nGgJt
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__v6OGy
                            )}
                          >
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__kyrVt)}
                              displayHeight={"auto"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/kinect_academy_inc/images/pexelsTimMossholder1154739Jpg.jpg",
                                fullWidth: 1920,
                                fullHeight: 1280,
                                aspectRatio: undefined
                              }}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__myZvX
                              )}
                            >
                              <Icon8Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__dD3Vn
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__eQfve
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__nkHbb
                              )}
                            >
                              {"Heading main Lorem"}
                            </h3>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___54GP
                              )}
                            >
                              {
                                "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the "
                              }
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__rd4Wv
                              )}
                            >
                              <Button color={"softYellow"} submitsForm={true}>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__a4AZw
                                  )}
                                >
                                  {"Read More"}
                                </div>
                              </Button>
                            </div>
                          </div>
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__n1Y0N
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__aqhT3
                            )}
                          >
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__ugm4V)}
                              displayHeight={"auto"}
                              displayMaxHeight={"none"}
                              displayMaxWidth={"100%"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: "/plasmic/kinect_academy_inc/images/pexelsSolomanSoh1492232Jpg.jpg",
                                fullWidth: 4000,
                                fullHeight: 2667,
                                aspectRatio: undefined
                              }}
                            />
                          </div>
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__t1Cqu
                              )}
                            >
                              <Icon8Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg___63ECr
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__d6QNe
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__lb0PY
                              )}
                            >
                              {"Heading main Lorem"}
                            </h3>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__onuE
                              )}
                            >
                              {
                                "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the "
                              }
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__q1Yqz
                              )}
                            >
                              <Button color={"softYellow"} submitsForm={true}>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__dkja2
                                  )}
                                >
                                  {"Read More"}
                                </div>
                              </Button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___0Es4Y)}>
            <div className={classNames(projectcss.all, sty.freeBox__dotqH)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hypMw
                )}
              >
                {"Accredited by:"}
              </div>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__q58GK
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Our Client brands"
                  : "We've been lucky to work with some great companies."}
              </h2>
              <div className={classNames(projectcss.all, sty.freeBox___44P7I)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__lx2D5)}
                  displayHeight={"98px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={{
                    src: "/plasmic/kinect_academy_inc/images/depEdLogoPng.png",
                    fullWidth: 3147,
                    fullHeight: 1523,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__lqqwg)}
                  displayHeight={"98px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={{
                    src: "/plasmic/kinect_academy_inc/images/tesdaPng.png",
                    fullWidth: 1950,
                    fullHeight: 525,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__a959L)}
                  displayHeight={"48px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={
                    "https://plasmic-ray.s3.us-west-2.amazonaws.com/logo-segment.svg"
                  }
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__aP3Ze)}
                  displayHeight={"48px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={
                    "https://plasmic-ray.s3.us-west-2.amazonaws.com/logo-xstate.svg"
                  }
                />
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox___2OaBb)}>
            <div className={classNames(projectcss.all, sty.freeBox__vt8K)}>
              <div className={classNames(projectcss.all, sty.freeBox__bdxWp)}>
                <div className={classNames(projectcss.all, sty.freeBox__koFiJ)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__qkqSd)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"200px"}
                    src={{
                      src: "/plasmic/kinect_academy_inc/images/kinectLogoLightPng.png",
                      fullWidth: 1800,
                      fullHeight: 636,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__exm18)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xXqD
                      )}
                    >
                      {"Connect with us"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___731Va
                      )}
                    >
                      <Icon19Icon
                        className={classNames(projectcss.all, sty.svg__hgIl7)}
                        onClick={async event => {
                          const $steps = {};

                          $steps["goToHttpsWwwFacebookComKinectacademyph"] =
                            true
                              ? (() => {
                                  const actionArgs = {
                                    destination:
                                      "https://www.facebook.com/kinectacademyph"
                                  };
                                  return (({ destination }) => {
                                    if (
                                      typeof destination === "string" &&
                                      destination.startsWith("#")
                                    ) {
                                      document
                                        .getElementById(destination.substr(1))
                                        .scrollIntoView({ behavior: "smooth" });
                                    } else {
                                      __nextRouter?.push(destination);
                                    }
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                          if (
                            $steps["goToHttpsWwwFacebookComKinectacademyph"] !=
                              null &&
                            typeof $steps[
                              "goToHttpsWwwFacebookComKinectacademyph"
                            ] === "object" &&
                            typeof $steps[
                              "goToHttpsWwwFacebookComKinectacademyph"
                            ].then === "function"
                          ) {
                            $steps["goToHttpsWwwFacebookComKinectacademyph"] =
                              await $steps[
                                "goToHttpsWwwFacebookComKinectacademyph"
                              ];
                          }
                        }}
                        role={"img"}
                      />

                      <Icon17Icon
                        className={classNames(projectcss.all, sty.svg__uCxm2)}
                        onClick={async event => {
                          const $steps = {};

                          $steps["goToHttpsMMeKinectacademyph"] = true
                            ? (() => {
                                const actionArgs = {
                                  destination: "https://m.me/kinectacademyph"
                                };
                                return (({ destination }) => {
                                  if (
                                    typeof destination === "string" &&
                                    destination.startsWith("#")
                                  ) {
                                    document
                                      .getElementById(destination.substr(1))
                                      .scrollIntoView({ behavior: "smooth" });
                                  } else {
                                    __nextRouter?.push(destination);
                                  }
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["goToHttpsMMeKinectacademyph"] != null &&
                            typeof $steps["goToHttpsMMeKinectacademyph"] ===
                              "object" &&
                            typeof $steps["goToHttpsMMeKinectacademyph"]
                              .then === "function"
                          ) {
                            $steps["goToHttpsMMeKinectacademyph"] =
                              await $steps["goToHttpsMMeKinectacademyph"];
                          }
                        }}
                        role={"img"}
                      />

                      <Icon20Icon
                        className={classNames(projectcss.all, sty.svg___0PsC)}
                        onClick={async event => {
                          const $steps = {};

                          $steps["goToHttpsWwwYoutubeComKinectacademyVideos"] =
                            true
                              ? (() => {
                                  const actionArgs = {
                                    destination:
                                      "https://www.youtube.com/@kinectacademy/videos"
                                  };
                                  return (({ destination }) => {
                                    if (
                                      typeof destination === "string" &&
                                      destination.startsWith("#")
                                    ) {
                                      document
                                        .getElementById(destination.substr(1))
                                        .scrollIntoView({ behavior: "smooth" });
                                    } else {
                                      __nextRouter?.push(destination);
                                    }
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                          if (
                            $steps[
                              "goToHttpsWwwYoutubeComKinectacademyVideos"
                            ] != null &&
                            typeof $steps[
                              "goToHttpsWwwYoutubeComKinectacademyVideos"
                            ] === "object" &&
                            typeof $steps[
                              "goToHttpsWwwYoutubeComKinectacademyVideos"
                            ].then === "function"
                          ) {
                            $steps[
                              "goToHttpsWwwYoutubeComKinectacademyVideos"
                            ] =
                              await $steps[
                                "goToHttpsWwwYoutubeComKinectacademyVideos"
                              ];
                          }
                        }}
                        role={"img"}
                      />
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__pyYqz)}>
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__d5BgN
                    )}
                  >
                    {"Navigation"}
                  </h3>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__yl4De
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__fuxdw)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___87DeK
                      )}
                    >
                      {"Nav link"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__kLgwx)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__lbsoX
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg___1CgU7)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__piavm
                      )}
                    >
                      {"Nav link"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__duLrd)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__fsZ4H
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__kzOoF)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rK6V
                      )}
                    >
                      {"Nav link"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__exbWu)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox___9NV8)}>
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3___5V5Pr
                    )}
                  >
                    {"Support"}
                  </h3>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__adjV8
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__sbVv9)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fuain
                      )}
                    >
                      {"Link"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__dFr4E)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__vilb7
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__cJvhH)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__oakwV
                      )}
                    >
                      {"FAQs"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg___7OeK)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__q1SSt
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__kve1M)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__etBeY
                      )}
                    >
                      {"Status"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__zPoE)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link___44W4C
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__zGl86)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mnJhu
                      )}
                    >
                      {"Link"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__wgmsF)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__r44Z)}>
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__xVsEr
                    )}
                  >
                    {"Address"}
                  </h3>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ji9H7
                    )}
                  >
                    {"574 Delos Reyes St.\nSan Vicente, Gapan City"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__i7Yp
                    )}
                  >
                    {"Phone:  0926.245.6828"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gj6Yp
                    )}
                  >
                    {"Email:  kinectacademy@gmail.com"}
                  </div>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qhxh6
                )}
              >
                <React.Fragment>
                  <React.Fragment>
                    {
                      "\u00a9 Kinect Academy Inc. All rights reserved. Site proudly built with "
                    }
                  </React.Fragment>
                  {
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        projectcss.plasmic_default__inline,
                        sty.link__p1MBu
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Plasmic"}
                    </PlasmicLink__>
                  }
                  <React.Fragment>{"."}</React.Fragment>
                </React.Fragment>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "foreground2",
    "registerLink",
    "reveal",
    "foreground",
    "foreground3"
  ],
  foreground2: ["foreground2", "registerLink"],
  registerLink: ["registerLink"],
  reveal: ["reveal", "foreground"],
  foreground: ["foreground"],
  foreground3: ["foreground3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  foreground2: "div";
  registerLink: typeof Button2;
  reveal: typeof Reveal;
  foreground: "div";
  foreground3: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAboutUs__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAboutUs__VariantsArgs;
    args?: PlasmicAboutUs__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicAboutUs__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicAboutUs__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAboutUs__ArgProps,
          internalVariantPropNames: PlasmicAboutUs__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAboutUs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAboutUs";
  } else {
    func.displayName = `PlasmicAboutUs.${nodeName}`;
  }
  return func;
}

export const PlasmicAboutUs = Object.assign(
  // Top-level PlasmicAboutUs renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    foreground2: makeNodeComponent("foreground2"),
    registerLink: makeNodeComponent("registerLink"),
    reveal: makeNodeComponent("reveal"),
    foreground: makeNodeComponent("foreground"),
    foreground3: makeNodeComponent("foreground3"),

    // Metadata about props expected for PlasmicAboutUs
    internalVariantProps: PlasmicAboutUs__VariantProps,
    internalArgProps: PlasmicAboutUs__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "About Us | Kinect Academy Inc.",
      description: "",
      ogImageSrc:
        "https://site-assets.plasmic.app/4c83f9f70da81d0a474d8d59d6e1dc3e.png",
      canonical: ""
    }
  }
);

export default PlasmicAboutUs;
/* prettier-ignore-end */
