/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qrgzy9hj6GGeC381EGfELp

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsj1IJkkG0ONnD } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: j1iJkkG0ONnD/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsj1IJkkG0ONnD
});
