/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qrgzy9hj6GGeC381EGfELp
// Component: 9gMHZ-ckU6UF

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button2 from "../../Button2"; // plasmic-import: 08WU9IokPT6n/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: qrgzy9hj6GGeC381EGfELp/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: qrgzy9hj6GGeC381EGfELp/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: qrgzy9hj6GGeC381EGfELp/projectcss
import sty from "./PlasmicContactUs.module.css"; // plasmic-import: 9gMHZ-ckU6UF/css

import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: HL2cx3XqKX6Z/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: XRWVBDzNjWYR/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: IdyPZ2PRL2vb/icon
import ArrowDownSvgIcon from "./icons/PlasmicIcon__ArrowDownSvg"; // plasmic-import: 2QZVkZITGcT-/icon
import Icon24Icon from "./icons/PlasmicIcon__Icon24"; // plasmic-import: T8x8EI9vPM_l/icon
import Icon25Icon from "./icons/PlasmicIcon__Icon25"; // plasmic-import: Kp5mIIUzZPt1/icon
import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: tq99IOsRzckU/icon
import Icon26Icon from "./icons/PlasmicIcon__Icon26"; // plasmic-import: 25NhfmlPo3iH/icon
import Icon19Icon from "./icons/PlasmicIcon__Icon19"; // plasmic-import: GloFZO7DAKCR/icon
import Icon17Icon from "./icons/PlasmicIcon__Icon17"; // plasmic-import: 7W9T4txEOvuQ/icon
import Icon20Icon from "./icons/PlasmicIcon__Icon20"; // plasmic-import: UKWF1bySvIgm/icon

createPlasmicElementProxy;

export type PlasmicContactUs__VariantMembers = {};
export type PlasmicContactUs__VariantsArgs = {};
type VariantPropType = keyof PlasmicContactUs__VariantsArgs;
export const PlasmicContactUs__VariantProps = new Array<VariantPropType>();

export type PlasmicContactUs__ArgsType = {};
type ArgPropType = keyof PlasmicContactUs__ArgsType;
export const PlasmicContactUs__ArgProps = new Array<ArgPropType>();

export type PlasmicContactUs__OverridesType = {
  root?: Flex__<"div">;
  button?: Flex__<"button">;
  foreground2?: Flex__<"div">;
  h1?: Flex__<"h1">;
  registerLink?: Flex__<typeof Button2>;
  reveal?: Flex__<typeof Reveal>;
  h2?: Flex__<"h2">;
  section?: Flex__<"section">;
  foreground?: Flex__<"div">;
};

export interface DefaultContactUsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicContactUs__RenderFunc(props: {
  variants: PlasmicContactUs__VariantsArgs;
  args: PlasmicContactUs__ArgsType;
  overrides: PlasmicContactUs__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicContactUs.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicContactUs.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          property="twitter:title"
          content={PlasmicContactUs.pageMetadata.title}
        />

        <meta
          key="og:image"
          property="og:image"
          content={PlasmicContactUs.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          property="twitter:image"
          content={PlasmicContactUs.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__qbpkT)}>
            <div className={classNames(projectcss.all, sty.freeBox__hf8Gt)}>
              <div className={classNames(projectcss.all, sty.freeBox___30Hu8)}>
                <div className={classNames(projectcss.all, sty.freeBox__wfoIr)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__e5XOe)}
                    displayHeight={"default"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"96px"}
                    src={{
                      src: "/plasmic/kinect_academy_inc/images/kinectIconLightPng.png",
                      fullWidth: 1000,
                      fullHeight: 1000,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__inrt6)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__kqa9M
                      )}
                      component={Link}
                      href={`/`}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__rpoRd)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__eB4Gp
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Services"
                          : "HOME"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__r6MB)}
                          role={"img"}
                        />
                      ) : null}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__sFygn
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__qWs2)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vjCyi
                        )}
                      >
                        {"Features"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___5XpCs
                          )}
                          role={"img"}
                        />
                      ) : null}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__kcm6T
                      )}
                      component={Link}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__a4RTn)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bzNbH
                        )}
                      >
                        {"work"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__yfPw7)}
                          role={"img"}
                        />
                      ) : null}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__hQa4Z
                      )}
                      component={Link}
                      href={`/contact`}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___6FanS
                          )}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___7QQfs
                        )}
                      >
                        {"Contact"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__xw6SQ)}
                          role={"img"}
                        />
                      ) : null}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__a7Im5
                      )}
                      component={Link}
                      href={`/about-us`}
                      legacyBehavior={false}
                      platform={"nextjs"}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__kV85D)}
                          role={"img"}
                        />
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__x2T4E
                        )}
                      >
                        {"About"}
                      </div>
                      {false ? (
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__w2UV7)}
                          role={"img"}
                        />
                      ) : null}
                    </PlasmicLink__>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__xF5Xl)}>
                  <button
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames(
                      projectcss.all,
                      projectcss.button,
                      projectcss.__wab_text,
                      sty.button
                    )}
                  >
                    {"Sign up"}
                  </button>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__dw8Hr
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__wgxpZ)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___2XahM
                      )}
                    >
                      {"Log in"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg___5NRpM)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"foreground2"}
              data-plasmic-override={overrides.foreground2}
              className={classNames(projectcss.all, sty.foreground2)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__nbo6)}>
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{"Join the "}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "var(--token-Dd6gyjIVe7XT)" }}
                    >
                      {"Kinect"}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#51D1FF" }}
                    >
                      {" Academy"}
                    </span>
                    <React.Fragment>{" Family!"}</React.Fragment>
                  </React.Fragment>
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tTmf
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "var(--token-Dd6gyjIVe7XT)" }}
                    >
                      {"SENIOR HIGH SCHOOL | GAPAN CITY"}
                    </span>
                  </React.Fragment>
                </div>
                <Button2
                  data-plasmic-name={"registerLink"}
                  data-plasmic-override={overrides.registerLink}
                  className={classNames("__wab_instance", sty.registerLink)}
                  disabled={false}
                  end={
                    <Icon6Icon
                      className={classNames(projectcss.all, sty.svg__lS35B)}
                      role={"img"}
                    />
                  }
                  iconEnd={true}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0BmGp
                      )}
                    >
                      {"REGISTER NOW"}
                    </div>
                  }
                  linkTo={"https://forms.gle/rse2ggxXWFjCuugY9"}
                  onClick={async event => {
                    const $steps = {};

                    $steps["runElementAction"] = true
                      ? (() => {
                          const actionArgs = {};
                          return (({ tplRef, action, args }) => {
                            return $refs?.[tplRef]?.[action]?.(...(args ?? []));
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["runElementAction"] != null &&
                      typeof $steps["runElementAction"] === "object" &&
                      typeof $steps["runElementAction"].then === "function"
                    ) {
                      $steps["runElementAction"] =
                        await $steps["runElementAction"];
                    }
                  }}
                  openLinkInNewTab={true}
                  roundedFull={true}
                  size={"small"}
                  start={
                    <Icon4Icon
                      className={classNames(projectcss.all, sty.svg__ybnsx)}
                      role={"img"}
                    />
                  }
                  type={"soft"}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__uYV)}>
                <ArrowDownSvgIcon
                  className={classNames(projectcss.all, sty.svg__kKOnx)}
                  role={"img"}
                />
              </div>
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__yr45C)}>
            <Reveal
              data-plasmic-name={"reveal"}
              data-plasmic-override={overrides.reveal}
              cascade={true}
              className={classNames("__wab_instance", sty.reveal)}
              triggerOnce={true}
            >
              <div className={classNames(projectcss.all, sty.freeBox__tj8XS)}>
                <div className={classNames(projectcss.all, sty.freeBox__haYy7)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wmRkq
                    )}
                  >
                    {"CONTACT US"}
                  </div>
                  <h2
                    data-plasmic-name={"h2"}
                    data-plasmic-override={overrides.h2}
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2
                    )}
                  >
                    {"Who is Kinect Academy ?"}
                  </h2>
                  <section
                    data-plasmic-name={"section"}
                    data-plasmic-override={overrides.section}
                    className={classNames(projectcss.all, sty.section)}
                  >
                    <div
                      data-plasmic-name={"foreground"}
                      data-plasmic-override={overrides.foreground}
                      className={classNames(projectcss.all, sty.foreground)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__xvKiv
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__sPhpb
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__zlETs
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__yZ66R
                              )}
                            >
                              <Icon24Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__urfzp
                                )}
                                onClick={async event => {
                                  const $steps = {};

                                  $steps["goToTel09262456828"] = true
                                    ? (() => {
                                        const actionArgs = {
                                          destination: "tel:0926-245-6828"
                                        };
                                        return (({ destination }) => {
                                          if (
                                            typeof destination === "string" &&
                                            destination.startsWith("#")
                                          ) {
                                            document
                                              .getElementById(
                                                destination.substr(1)
                                              )
                                              .scrollIntoView({
                                                behavior: "smooth"
                                              });
                                          } else {
                                            __nextRouter?.push(destination);
                                          }
                                        })?.apply(null, [actionArgs]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps["goToTel09262456828"] != null &&
                                    typeof $steps["goToTel09262456828"] ===
                                      "object" &&
                                    typeof $steps["goToTel09262456828"].then ===
                                      "function"
                                  ) {
                                    $steps["goToTel09262456828"] =
                                      await $steps["goToTel09262456828"];
                                  }
                                }}
                                role={"img"}
                              />
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__pjIl3
                              )}
                            >
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__qkg9Z
                                )}
                              >
                                {"Call Us"}
                              </h3>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__kPjLk
                                )}
                                onClick={async event => {
                                  const $steps = {};

                                  $steps["goToTel09262456828"] = true
                                    ? (() => {
                                        const actionArgs = {
                                          destination: "tel:0926-245-6828"
                                        };
                                        return (({ destination }) => {
                                          if (
                                            typeof destination === "string" &&
                                            destination.startsWith("#")
                                          ) {
                                            document
                                              .getElementById(
                                                destination.substr(1)
                                              )
                                              .scrollIntoView({
                                                behavior: "smooth"
                                              });
                                          } else {
                                            __nextRouter?.push(destination);
                                          }
                                        })?.apply(null, [actionArgs]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps["goToTel09262456828"] != null &&
                                    typeof $steps["goToTel09262456828"] ===
                                      "object" &&
                                    typeof $steps["goToTel09262456828"].then ===
                                      "function"
                                  ) {
                                    $steps["goToTel09262456828"] =
                                      await $steps["goToTel09262456828"];
                                  }
                                }}
                              >
                                {"0926.245.6828"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__g4R6W
                                )}
                                onClick={async event => {
                                  const $steps = {};

                                  $steps["goToTel0443295030"] = true
                                    ? (() => {
                                        const actionArgs = {
                                          destination: "tel:044-329-5030"
                                        };
                                        return (({ destination }) => {
                                          if (
                                            typeof destination === "string" &&
                                            destination.startsWith("#")
                                          ) {
                                            document
                                              .getElementById(
                                                destination.substr(1)
                                              )
                                              .scrollIntoView({
                                                behavior: "smooth"
                                              });
                                          } else {
                                            __nextRouter?.push(destination);
                                          }
                                        })?.apply(null, [actionArgs]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps["goToTel0443295030"] != null &&
                                    typeof $steps["goToTel0443295030"] ===
                                      "object" &&
                                    typeof $steps["goToTel0443295030"].then ===
                                      "function"
                                  ) {
                                    $steps["goToTel0443295030"] =
                                      await $steps["goToTel0443295030"];
                                  }
                                }}
                              >
                                {"044.329.5030"}
                              </div>
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__aFQhV
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__grQUq
                              )}
                            >
                              <Icon25Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__bF1
                                )}
                                onClick={async event => {
                                  const $steps = {};

                                  $steps[
                                    "goToHttpsMapsAppGooGlEEzmquvtk5Qbx9O8A"
                                  ] = true
                                    ? (() => {
                                        const actionArgs = {
                                          destination:
                                            "https://maps.app.goo.gl/eEZMQUVTK5qbx9o8A"
                                        };
                                        return (({ destination }) => {
                                          if (
                                            typeof destination === "string" &&
                                            destination.startsWith("#")
                                          ) {
                                            document
                                              .getElementById(
                                                destination.substr(1)
                                              )
                                              .scrollIntoView({
                                                behavior: "smooth"
                                              });
                                          } else {
                                            __nextRouter?.push(destination);
                                          }
                                        })?.apply(null, [actionArgs]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps[
                                      "goToHttpsMapsAppGooGlEEzmquvtk5Qbx9O8A"
                                    ] != null &&
                                    typeof $steps[
                                      "goToHttpsMapsAppGooGlEEzmquvtk5Qbx9O8A"
                                    ] === "object" &&
                                    typeof $steps[
                                      "goToHttpsMapsAppGooGlEEzmquvtk5Qbx9O8A"
                                    ].then === "function"
                                  ) {
                                    $steps[
                                      "goToHttpsMapsAppGooGlEEzmquvtk5Qbx9O8A"
                                    ] =
                                      await $steps[
                                        "goToHttpsMapsAppGooGlEEzmquvtk5Qbx9O8A"
                                      ];
                                  }
                                }}
                                role={"img"}
                              />
                            </div>
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__shHue
                                )}
                              >
                                <Icon8Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__mGDq
                                  )}
                                  role={"img"}
                                />
                              </div>
                            ) : null}
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___9NlV
                              )}
                            >
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3___0Lmnd
                                )}
                              >
                                {"Visit Us"}
                              </h3>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text___3Seaz
                                )}
                                onClick={async event => {
                                  const $steps = {};

                                  $steps[
                                    "goToHttpsMapsAppGooGlEEzmquvtk5Qbx9O8A"
                                  ] = true
                                    ? (() => {
                                        const actionArgs = {
                                          destination:
                                            "https://maps.app.goo.gl/eEZMQUVTK5qbx9o8A"
                                        };
                                        return (({ destination }) => {
                                          if (
                                            typeof destination === "string" &&
                                            destination.startsWith("#")
                                          ) {
                                            document
                                              .getElementById(
                                                destination.substr(1)
                                              )
                                              .scrollIntoView({
                                                behavior: "smooth"
                                              });
                                          } else {
                                            __nextRouter?.push(destination);
                                          }
                                        })?.apply(null, [actionArgs]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps[
                                      "goToHttpsMapsAppGooGlEEzmquvtk5Qbx9O8A"
                                    ] != null &&
                                    typeof $steps[
                                      "goToHttpsMapsAppGooGlEEzmquvtk5Qbx9O8A"
                                    ] === "object" &&
                                    typeof $steps[
                                      "goToHttpsMapsAppGooGlEEzmquvtk5Qbx9O8A"
                                    ].then === "function"
                                  ) {
                                    $steps[
                                      "goToHttpsMapsAppGooGlEEzmquvtk5Qbx9O8A"
                                    ] =
                                      await $steps[
                                        "goToHttpsMapsAppGooGlEEzmquvtk5Qbx9O8A"
                                      ];
                                  }
                                }}
                              >
                                {"574 Delos Reyes St.\nSan Vicente, Gapan City"}
                              </div>
                            </div>
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__vPbKp
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__p5PvB
                              )}
                            >
                              <Icon26Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__rYpKr
                                )}
                                role={"img"}
                              />
                            </div>
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__zU6Px
                                )}
                              >
                                <Icon8Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__wR1Li
                                  )}
                                  role={"img"}
                                />
                              </div>
                            ) : null}
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__mQrTh
                              )}
                            >
                              <h3
                                className={classNames(
                                  projectcss.all,
                                  projectcss.h3,
                                  projectcss.__wab_text,
                                  sty.h3__ohfip
                                )}
                              >
                                {"Social Media"}
                              </h3>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__f3Qau
                                )}
                                onClick={async event => {
                                  const $steps = {};

                                  $steps[
                                    "goToHttpsWwwFacebookComKinectacademyph"
                                  ] = true
                                    ? (() => {
                                        const actionArgs = {
                                          destination:
                                            "https://www.facebook.com/kinectacademyph"
                                        };
                                        return (({ destination }) => {
                                          if (
                                            typeof destination === "string" &&
                                            destination.startsWith("#")
                                          ) {
                                            document
                                              .getElementById(
                                                destination.substr(1)
                                              )
                                              .scrollIntoView({
                                                behavior: "smooth"
                                              });
                                          } else {
                                            __nextRouter?.push(destination);
                                          }
                                        })?.apply(null, [actionArgs]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps[
                                      "goToHttpsWwwFacebookComKinectacademyph"
                                    ] != null &&
                                    typeof $steps[
                                      "goToHttpsWwwFacebookComKinectacademyph"
                                    ] === "object" &&
                                    typeof $steps[
                                      "goToHttpsWwwFacebookComKinectacademyph"
                                    ].then === "function"
                                  ) {
                                    $steps[
                                      "goToHttpsWwwFacebookComKinectacademyph"
                                    ] =
                                      await $steps[
                                        "goToHttpsWwwFacebookComKinectacademyph"
                                      ];
                                  }
                                }}
                              >
                                {"facebook.com/kinectacademyph"}
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__kB1Ei
                                )}
                                onClick={async event => {
                                  const $steps = {};

                                  $steps[
                                    "goToHttpsWwwYoutubeComKinectacademy"
                                  ] = true
                                    ? (() => {
                                        const actionArgs = {
                                          destination:
                                            "https://www.youtube.com/@kinectacademy"
                                        };
                                        return (({ destination }) => {
                                          if (
                                            typeof destination === "string" &&
                                            destination.startsWith("#")
                                          ) {
                                            document
                                              .getElementById(
                                                destination.substr(1)
                                              )
                                              .scrollIntoView({
                                                behavior: "smooth"
                                              });
                                          } else {
                                            __nextRouter?.push(destination);
                                          }
                                        })?.apply(null, [actionArgs]);
                                      })()
                                    : undefined;
                                  if (
                                    $steps[
                                      "goToHttpsWwwYoutubeComKinectacademy"
                                    ] != null &&
                                    typeof $steps[
                                      "goToHttpsWwwYoutubeComKinectacademy"
                                    ] === "object" &&
                                    typeof $steps[
                                      "goToHttpsWwwYoutubeComKinectacademy"
                                    ].then === "function"
                                  ) {
                                    $steps[
                                      "goToHttpsWwwYoutubeComKinectacademy"
                                    ] =
                                      await $steps[
                                        "goToHttpsWwwYoutubeComKinectacademy"
                                      ];
                                  }
                                }}
                              >
                                {"youtube.com/@kinectacademy"}
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </section>
                </div>
              </div>
            </Reveal>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__fZyzA)}>
            <div className={classNames(projectcss.all, sty.freeBox__pIhFd)}>
              <div className={classNames(projectcss.all, sty.freeBox___4Urv7)}>
                <div className={classNames(projectcss.all, sty.freeBox__kRfE)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__dzjSc)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"200px"}
                    src={{
                      src: "/plasmic/kinect_academy_inc/images/kinectLogoLightPng.png",
                      fullWidth: 1800,
                      fullHeight: 636,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox___4V2QN)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__s0So
                      )}
                    >
                      {"Connect with us"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__m5Jt)}
                    >
                      <Icon19Icon
                        className={classNames(projectcss.all, sty.svg__aaHmO)}
                        onClick={async event => {
                          const $steps = {};

                          $steps["goToHttpsWwwFacebookComKinectacademyph"] =
                            true
                              ? (() => {
                                  const actionArgs = {
                                    destination:
                                      "https://www.facebook.com/kinectacademyph"
                                  };
                                  return (({ destination }) => {
                                    if (
                                      typeof destination === "string" &&
                                      destination.startsWith("#")
                                    ) {
                                      document
                                        .getElementById(destination.substr(1))
                                        .scrollIntoView({ behavior: "smooth" });
                                    } else {
                                      __nextRouter?.push(destination);
                                    }
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                          if (
                            $steps["goToHttpsWwwFacebookComKinectacademyph"] !=
                              null &&
                            typeof $steps[
                              "goToHttpsWwwFacebookComKinectacademyph"
                            ] === "object" &&
                            typeof $steps[
                              "goToHttpsWwwFacebookComKinectacademyph"
                            ].then === "function"
                          ) {
                            $steps["goToHttpsWwwFacebookComKinectacademyph"] =
                              await $steps[
                                "goToHttpsWwwFacebookComKinectacademyph"
                              ];
                          }
                        }}
                        role={"img"}
                      />

                      <Icon17Icon
                        className={classNames(projectcss.all, sty.svg__pBeDu)}
                        onClick={async event => {
                          const $steps = {};

                          $steps["goToHttpsMMeKinectacademyph"] = true
                            ? (() => {
                                const actionArgs = {
                                  destination: "https://m.me/kinectacademyph"
                                };
                                return (({ destination }) => {
                                  if (
                                    typeof destination === "string" &&
                                    destination.startsWith("#")
                                  ) {
                                    document
                                      .getElementById(destination.substr(1))
                                      .scrollIntoView({ behavior: "smooth" });
                                  } else {
                                    __nextRouter?.push(destination);
                                  }
                                })?.apply(null, [actionArgs]);
                              })()
                            : undefined;
                          if (
                            $steps["goToHttpsMMeKinectacademyph"] != null &&
                            typeof $steps["goToHttpsMMeKinectacademyph"] ===
                              "object" &&
                            typeof $steps["goToHttpsMMeKinectacademyph"]
                              .then === "function"
                          ) {
                            $steps["goToHttpsMMeKinectacademyph"] =
                              await $steps["goToHttpsMMeKinectacademyph"];
                          }
                        }}
                        role={"img"}
                      />

                      <Icon20Icon
                        className={classNames(projectcss.all, sty.svg__u7Dn2)}
                        onClick={async event => {
                          const $steps = {};

                          $steps["goToHttpsWwwYoutubeComKinectacademyVideos"] =
                            true
                              ? (() => {
                                  const actionArgs = {
                                    destination:
                                      "https://www.youtube.com/@kinectacademy/videos"
                                  };
                                  return (({ destination }) => {
                                    if (
                                      typeof destination === "string" &&
                                      destination.startsWith("#")
                                    ) {
                                      document
                                        .getElementById(destination.substr(1))
                                        .scrollIntoView({ behavior: "smooth" });
                                    } else {
                                      __nextRouter?.push(destination);
                                    }
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                          if (
                            $steps[
                              "goToHttpsWwwYoutubeComKinectacademyVideos"
                            ] != null &&
                            typeof $steps[
                              "goToHttpsWwwYoutubeComKinectacademyVideos"
                            ] === "object" &&
                            typeof $steps[
                              "goToHttpsWwwYoutubeComKinectacademyVideos"
                            ].then === "function"
                          ) {
                            $steps[
                              "goToHttpsWwwYoutubeComKinectacademyVideos"
                            ] =
                              await $steps[
                                "goToHttpsWwwYoutubeComKinectacademyVideos"
                              ];
                          }
                        }}
                        role={"img"}
                      />
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__i1ThV)}>
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__zI5K7
                    )}
                  >
                    {"Navigation"}
                  </h3>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__ehq7Q
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__cq9SW)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___1CSuo
                      )}
                    >
                      {"Nav link"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__wAti5)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__bjt6I
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__bCo)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xhuzH
                      )}
                    >
                      {"Nav link"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__s3EoQ)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__sV53X
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__hIPog)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__d8ZlB
                      )}
                    >
                      {"Nav link"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__v7D22)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox___0WaY)}>
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3___8Ih7A
                    )}
                  >
                    {"Support"}
                  </h3>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__yjQ9J
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg___26WDz)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__q08B
                      )}
                    >
                      {"Link"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__x7FCx)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link___4ZaBq
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__jkNli)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wnLyq
                      )}
                    >
                      {"FAQs"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__s0Ha5)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__wIc61
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__vU1Zk)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kPqby
                      )}
                    >
                      {"Status"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__nJiL)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__a0Nne
                    )}
                    component={Link}
                    legacyBehavior={false}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__kDbH7)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tlrtD
                      )}
                    >
                      {"Link"}
                    </div>
                    {false ? (
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__tKjUc)}
                        role={"img"}
                      />
                    ) : null}
                  </PlasmicLink__>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__zsfSy)}>
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3___7SOvi
                    )}
                  >
                    {"Address"}
                  </h3>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__s3Rn6
                    )}
                  >
                    {"574 Delos Reyes St.\nSan Vicente, Gapan City"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wy2Py
                    )}
                  >
                    {"Phone:  0926.245.6828"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qeBkI
                    )}
                  >
                    {"Email:  kinectacademy@gmail.com"}
                  </div>
                </div>
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___2EFJw
                )}
              >
                {"\u00a9 Kinect Academy Inc. All rights reserved."}
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "button",
    "foreground2",
    "h1",
    "registerLink",
    "reveal",
    "h2",
    "section",
    "foreground"
  ],
  button: ["button"],
  foreground2: ["foreground2", "h1", "registerLink"],
  h1: ["h1"],
  registerLink: ["registerLink"],
  reveal: ["reveal", "h2", "section", "foreground"],
  h2: ["h2"],
  section: ["section", "foreground"],
  foreground: ["foreground"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  button: "button";
  foreground2: "div";
  h1: "h1";
  registerLink: typeof Button2;
  reveal: typeof Reveal;
  h2: "h2";
  section: "section";
  foreground: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicContactUs__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicContactUs__VariantsArgs;
    args?: PlasmicContactUs__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicContactUs__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicContactUs__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicContactUs__ArgProps,
          internalVariantPropNames: PlasmicContactUs__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicContactUs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicContactUs";
  } else {
    func.displayName = `PlasmicContactUs.${nodeName}`;
  }
  return func;
}

export const PlasmicContactUs = Object.assign(
  // Top-level PlasmicContactUs renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    button: makeNodeComponent("button"),
    foreground2: makeNodeComponent("foreground2"),
    h1: makeNodeComponent("h1"),
    registerLink: makeNodeComponent("registerLink"),
    reveal: makeNodeComponent("reveal"),
    h2: makeNodeComponent("h2"),
    section: makeNodeComponent("section"),
    foreground: makeNodeComponent("foreground"),

    // Metadata about props expected for PlasmicContactUs
    internalVariantProps: PlasmicContactUs__VariantProps,
    internalArgProps: PlasmicContactUs__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Contact Us | Kinect Academy Inc.",
      description: "",
      ogImageSrc:
        "https://site-assets.plasmic.app/4c83f9f70da81d0a474d8d59d6e1dc3e.png",
      canonical: ""
    }
  }
);

export default PlasmicContactUs;
/* prettier-ignore-end */
